title: "Hello, world! I'm geecici"
description: "This is my blog."
permalink: ':title/'
#baseurl: "/"
url: "https://geecici.github.io"

# Author Settings
author: geecici
author-img: geecici.png
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning.
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: geecici
linkedin: # add your Linkedin handle
email: zhangjanny@foxmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
